name: lab005 CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++ libgtest-dev

      - name: Build and test
        run: |
          cd /usr/src/gtest
          sudo cmake .
          sudo make
          sudo cp *.a /usr/lib
          cd $GITHUB_WORKSPACE
          cmake .
          make
          ctest --output-on-failure
